---
title: "solutions session 7"
format: html
---

## Exercises 1

1. Get the table with 2023 opinion polling for the next United Kingdom general election from <https://en.wikipedia.org/w/index.php?title=Opinion_polling_for_the_2024_United_Kingdom_general_election&oldid=1232596394>
2. Wrangle and plot the data opinion polls

## Exercises 2

1. For extracting text, `rvest` has two functions: `html_text` and `html_text2`. Explain the difference. You can test your explanation with the example html below.

```{r}
html <- "<p>This is some text
         some more text</p><p>A new paragraph!</p>
         <p>Quick Question, is web scraping:

         a) fun
         b) tedious
         c) I'm not sure yet!</p>" |>
  read_html()
```

2. How could you convert the `links` objects so that it contains actual URLs?
3. How could you add the links we extracted above to the `pm_table` to keep everything together?

## Exercises 3

We might be interested in product specific rating scales (sound, comfort, and quality)

1. Extract that information from the first review page (hint: it works similar to the star rating and you can reuse that function)
2. Each review has 3 feature ratings, extract the labels to those ratings and combine them with the ratings themselves into a data.frame
3. Add the variables sound, comfort, and quality to the `parse_review` function (hint: you will need `pivot_wider`)
4. Create `all_reviews` again, but with the feature ratings this time

## Exercises 4

1. Get the author, publication datetime, headline and text from this site: <https://www.cnet.com/tech/services-and-software/facebook-hopes-to-normalize-idea-of-data-scraping-leaks-says-leaked-internal-memo/> (hint: it works in a very similar way, but you have to apply one extra data wrangling step)

## Exercises 5

First, review the material. What you should take from this section:

- websites might contain files containing the data you are interested in. Scraping the links and then downloading the files is a quick way to get access
- It is possible to extract data from PDFs, but not trivial
- The package `pdftools` has a `pdf_data` function which gives you much more flexibility to extract information systematically than `pdf_text`

That said, you can practice working with PDFs a litte

1. In the folder /data (relative to this document) there is a PDF with some text. Read it into R
2. The PDF has two columns, parse the left column of the first page into one object and the right into another
3. Now combine them and bring the text in the right order as a human would read it

Bonus:

4. Let's assume you wanted to have this text in a table with one column indicating the section and one having the text of the section
5. Now let's assume you wanted to parse this on the paragraph level instead (hint: remember `str_split`)

