---
title: "solutions session 1"
format: html
---

## Exercises 2

1. Run ggplot(data = mtcars). What do you see and why?
2. In the function `pb_collect()` from `paperboy`, what do the arguments `ignore_fails` and `connections` do?
3. Write a function that takes a numeric vector of miles per gallon consumption data and transforms it to kilometer per liter. If anything other than a numeric vector is entered, the function should display an error (hint: see ?stop).
4. In the code below, check the sizes of the intermediate objects with `object.size()`.

```{r}
file_link <- "https://raw.githubusercontent.com/shawn-y-sun/Customer_Analytics_Retail/main/purchase%20data.csv"
df <- read.csv(file_link)
filtered_df <- df[df$Age >= 50,]
aggregated_df <- aggregate(filtered_df$Quantity, by = list(filtered_df$Day), FUN = sum)
names(aggregated_df) <- c("day", "total_quantity")
aggregated_df[order(aggregated_df$total_quantity, decreasing = TRUE)[1:5],]
```

5. How could the code above be improved if you only want the final result, the code should be readable and you care about memory usage?

## Exercises 4

1. Use the function `report_template()` from my package [jbgtemplates](https://github.com/JBGruber/jbgtemplates) to start a new report
2. Add some simple analysis in it and render
3. Play around with the [formats](https://quarto.org/docs/output-formats/all-formats.html) and produce at least a PDF and Word output of your document
4. Think about how the structure of the document enhances reproducibility
