---
title: "solutions session 5"
format: html
---

## Exercises 1

Using the `PostgreSQL` database or the `SQLite` database from session 4:

1. Right join `results_state` and `facts` using `dbplyr` instead of `dbGetQuery`
2. Recreate the table `results_state_time` by querying and joining from db (using `dbplyr` instead of `dbGetQuery`).
3. Recreate `results_state_facts` using `dbplyr`. Don't forget to add `total_votes` and `pct_votes`
4. Extract the SQL query from your code in 3. and run it with `dbGetQuery`

## Exercises 2

1. Connect to your own AmCAT server (alternatively,  connect to mine)
2. Create a new index and add some toy data to it that has: a date, a title, and a text field
3. Query all documents from your index
4. query the documents from the "houseofcommons" index that have:
   1) mentions of protest, protesters, protester, or protesting
   2) no mentions of protestant, in addition to 4.1
   3) contain speeches by the Conservative Party, in addition to 4.1 and 4.2 (hint: use a filter)
5. Count (hint: aggregate) how often the Conservatives mention protest words each month after 2000
