---
title: "solutions session 8"
format: html
---

## Exercises 1

First, review the material and make sure you have a broad understanding how to:

- build a request to an API
- perform the request
- handle the response


1. `httr2` has several more functions to customize how a request is performed. What do these functions do?

- `req_throttle`:
- `req_error`:
- `req_retry`:

2. Make your own request to the API with a different search term

3. You might want to add more information to the data.frame. Adapt the function parse_response to also extract: apiUrl, lastModifiedDate, pillarId

4. Request page 2 from the API. You can search for the correct query parameter in the documentation here: <https://open-platform.theguardian.com/documentation/>


## Exercises 2

First, review the material and make sure you have a broad understanding how to:

- read the documentation of the UK Parliament API (the documentation is specific to the API, but the Swagger format they use is very common)
- how to translate a curl call
- What the individual parts of the `search_members` function are doing

To get more information about an MP, we can use the endpoint "/api/Members/{id}/Biography"

1. Search for an MP you are interested in with the function above and use the id on the documentation website with "Try it out"
2. Copy the Curl call and translate it into `httr2` code
3. Wrangle the `governmentPosts` returned in the data into a tabular format

Bonus:

4. Write a function which lets you request information given an ID and which wrangles the results
5. Two more interesting endpoints are "/api/Posts/GovernmentPosts" and "/api/Posts/OppositionPosts". What do they do and how can you request data from them

